version: 2

jobs:
  install:
    docker:
      - image: cimg/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "package-lock.json" }}
            - v12-dependencies-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v12-dependencies-{{ checksum "package-lock.json" }}

  lint:
    docker:
      - image: cimg/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Linting
          command: npm run lint

  test-mocha:
    docker:
      - image: cimg/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test with Mocha
          command: npm run test

  test-jest:
    docker:
      - image: cimg/node:14.17.5-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v12-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test with Jest
          command: npm run test-jest

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test-mocha:
          requires:
            - install
      - test-jest:
          requires:
            - install