version: 2

jobs:
  install:
    docker:
      - image: cimg/node:18.17.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v18-dependencies-{{ checksum "package-lock.json" }}
            - v18-dependencies-
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save_cache:
          paths:
            - node_modules
          key: v18-dependencies-{{ checksum "package-lock.json" }}

  lint:
    docker:
      - image: cimg/node:18.17.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v18-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Linting
          command: npm run lint

  audit:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v18-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Security audit
          command: npm audit

  test:
    docker:
      - image: cimg/node:18.17.1-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v18-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: |
            node node_modules/puppeteer/install.mjs
            npm run test

workflows:
  version: 2
  build:
    jobs:
      - install
      - lint:
          requires:
            - install
      - audit:
          requires:
            - install
      - test:
          requires:
            - install