name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          release-type: node
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install
        run: yarn
      - name: Publish
        env:
          NPM_API_TOKEN: ${{ secrets.NPM_API_TOKEN }}
        run: |
          npm set //registry.npmjs.org/:_authToken $NPM_API_TOKEN
          npm publish --access=public
